openapi: 3.0.0

info:
  version: 1.0.0
  title: ""

# servers:
#   - url: https://api.journettobecomeepic.com/shards/{platform}
#     variables:
#       "platform":
#         enum:
#         - "kakao"
#         - "psn"
#         - "stadia"
#         - "steam"
#         - "xbox"
#         default: steam

servers:
  - url: https://api.journettobecomeepic.com/shards/{platform}
    variables:
      "platform":
        enum:
        - "kakao"
        - "psn"
        - "stadia"
        - "steam"
        - "xbox"
        default: steam
security:
  - ApiKeyAuth: []

paths:
  /accounts:
    $ref: './paths/index.yml#/players'

  /accounts/{accountId}:
    $ref: './paths/index.yml#/player'

components:
  securitySchemes:
    ApiKeyAuth:
      type: http
      description: "Enter your API key here to be used with the interactive documentation!"
      scheme: bearer
      bearerFormat: JWT

  schemas:
    player:
      $ref: 'schemas/index.yml#/player'
    # gameModes:
    #   $ref: 'schemas/index.yml#/gaemModes'
