openapi: 3.0.0

info:
  version: 1.0.0
  title: ""

servers:
  - url: https://api.epic-journey.com/id/v1/

security:
  - ApiKeyAuth: []

paths:
  /accounts:
    $ref: './paths/index.yml#/accounts'

  /accounts/{accountId}:
    $ref: './paths/index.yml#/account'

components:
  securitySchemes:
    ApiKeyAuth:
      type: http
      description: "Enter your API key here to be used with the interactive documentation!"
      scheme: bearer
      bearerFormat: JWT

  schemas:
    account:
      $ref: 'schemas/index.yml#/account'
