openapi: 3.0.0

info:
  version: 1.0.0
  title: "List Game modes on players region"

servers:
  - url: https://api.journettobecomeepic.com
    variables:
      "platform":
        enum:
        - "psn"
        - "stadia"
        - "steam"
        - "xbox"
        default: psn
security:
  - ApiKeyAuth: []

paths:
  /gameModes:
    $ref: './paths/index.yml#/gameModes'

components:
  securitySchemes:
    ApiKeyAuth:
      type: http
      description: "Enter your API key here to be used with the interactive documentation!"
      scheme: bearer
      bearerFormat: JWT

  schemas:
    gameMode:
      $ref: 'schemas/index.yml#/gameMode'
