openapi: 3.0.0

info:
  version: 1.0.0
  title: "List Game modes on player's region"

servers:
    # URL could be if we combine "platform" and "region" together: https://api.epic-journey.com/game/v1/{titleId}/{platform+region}/gameModes
  - url: https://api.epic-journey.com/game/v1/{titleId}/{platform}/{region}/gameModes
    variables:
      titleId:
        default: "epic-journey-id"
        description: "N/A"
      platform:
       enum:
       - "psn"
       - "xbox"
       default: psn
      region:
        enum:
        - "eu"
        - "as"
        default: eu

security:
  - ApiKeyAuth: []

paths:
  /gameModes:
    $ref: './paths/index.yml#/gameModes'

components:
  securitySchemes:
    ApiKeyAuth:
      type: http
      description: "Enter your API key here to be used with the interactive documentation!"
      scheme: bearer
      bearerFormat: JWT

  schemas:
    gameMode:
      $ref: 'schemas/index.yml#/gameMode'
